package presentation;
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kevin
 */


public class View extends javax.swing.JFrame {
String usertype = "Regular";

    /**
     * Creates new form View
     */
    public View() {
       
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MainPage = new javax.swing.JFrame();
        PropietyTitle = new javax.swing.JLabel();
        MainPagePanel = new javax.swing.JPanel();
        NameHereText = new javax.swing.JLabel();
        ThingsHereText = new javax.swing.JLabel();
        ViewButton = new javax.swing.JButton();
        AddPropertyPage = new javax.swing.JFrame();
        BackLAddProp = new javax.swing.JButton();
        NewPropTitle = new javax.swing.JLabel();
        NumbBedText = new javax.swing.JLabel();
        NumbBedSpinner = new javax.swing.JSpinner();
        FurnishedBox = new javax.swing.JCheckBox();
        QuadrantText = new javax.swing.JLabel();
        QuadrantInputBox = new javax.swing.JComboBox<>();
        PropertyTypeNewPropText = new javax.swing.JLabel();
        PropTypeNewPropField = new javax.swing.JTextField();
        PriceText = new javax.swing.JLabel();
        PriceField = new javax.swing.JTextField();
        NewPropSubmitButton = new javax.swing.JButton();
        PayFeesPage = new javax.swing.JFrame();
        BackLPayFees = new javax.swing.JButton();
        EditListingPageLandlord = new javax.swing.JFrame();
        BackLEditListing = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegisterPage = new javax.swing.JFrame();
        RegisterTitle = new javax.swing.JLabel();
        EmailRegisterField = new javax.swing.JTextField();
        EmailRegisterText = new javax.swing.JLabel();
        PasswordRegisterText = new javax.swing.JLabel();
        RegisterRegisterButton = new javax.swing.JButton();
        ResetRegisterButton = new javax.swing.JButton();
        ComboRegisterBox = new javax.swing.JComboBox<>();
        AccountRegisterType = new javax.swing.JLabel();
        PasswordRegisterField = new javax.swing.JPasswordField();
        ChangeFeesPage = new javax.swing.JFrame();
        BackFees = new javax.swing.JButton();
        AdminDashboardPage = new javax.swing.JFrame();
        AdminDashboardText = new javax.swing.JLabel();
        GoMainPageAdminButton = new javax.swing.JButton();
        EditListingsAdminButton = new javax.swing.JButton();
        ChnageFeesButton = new javax.swing.JButton();
        RequestSummmaryButton = new javax.swing.JButton();
        LandlordDashboardPage = new javax.swing.JFrame();
        LandlordDashboardTitle = new javax.swing.JLabel();
        RegisterPropertyLandlord = new javax.swing.JButton();
        PayFeesLandlord = new javax.swing.JButton();
        EditListingsLandlord = new javax.swing.JButton();
        LoginPage = new javax.swing.JFrame();
        LoginText = new javax.swing.JLabel();
        UsernameText = new javax.swing.JLabel();
        PasswordText = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        ResultText = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        EditListingPageAdmin = new javax.swing.JFrame();
        BackAEditListings = new javax.swing.JButton();
        LoginHomeButton = new javax.swing.JToggleButton();
        RegisterHomeButton = new javax.swing.JToggleButton();
        EnterHomeButton = new javax.swing.JToggleButton();
        WelcomeText = new javax.swing.JLabel();

        PropietyTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PropietyTitle.setText("Propieties");

        MainPagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NameHereText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NameHereText.setText("Name Here");

        ThingsHereText.setText("Things here");

        ViewButton.setText("View");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPagePanelLayout = new javax.swing.GroupLayout(MainPagePanel);
        MainPagePanel.setLayout(MainPagePanelLayout);
        MainPagePanelLayout.setHorizontalGroup(
            MainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPagePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(MainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ThingsHereText, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(NameHereText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewButton)
                .addContainerGap())
        );
        MainPagePanelLayout.setVerticalGroup(
            MainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameHereText, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ThingsHereText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(ViewButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPageLayout = new javax.swing.GroupLayout(MainPage.getContentPane());
        MainPage.getContentPane().setLayout(MainPageLayout);
        MainPageLayout.setHorizontalGroup(
            MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPageLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PropietyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainPagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        MainPageLayout.setVerticalGroup(
            MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPageLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(PropietyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainPagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        BackLAddProp.setText("Back");
        BackLAddProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackLAddPropActionPerformed(evt);
            }
        });

        NewPropTitle.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        NewPropTitle.setText("New Property");

        NumbBedText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        NumbBedText.setText("Number of bedrooms");

        FurnishedBox.setText("Furnished");

        QuadrantText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        QuadrantText.setText("Quadrant");

        QuadrantInputBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NW", "SW", "NE", "SE" }));

        PropertyTypeNewPropText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        PropertyTypeNewPropText.setText("Property type");

        PriceText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        PriceText.setText("Price");

        NewPropSubmitButton.setText("Submit");

        javax.swing.GroupLayout AddPropertyPageLayout = new javax.swing.GroupLayout(AddPropertyPage.getContentPane());
        AddPropertyPage.getContentPane().setLayout(AddPropertyPageLayout);
        AddPropertyPageLayout.setHorizontalGroup(
            AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPropertyPageLayout.createSequentialGroup()
                .addGroup(AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPropertyPageLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(NewPropTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(AddPropertyPageLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FurnishedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddPropertyPageLayout.createSequentialGroup()
                                .addGroup(AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumbBedText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuadrantText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PropertyTypeNewPropText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewPropSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumbBedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuadrantInputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PropTypeNewPropField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(96, 96, 96)))
                .addComponent(BackLAddProp)
                .addGap(18, 18, 18))
        );
        AddPropertyPageLayout.setVerticalGroup(
            AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPropertyPageLayout.createSequentialGroup()
                .addGroup(AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPropertyPageLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BackLAddProp))
                    .addGroup(AddPropertyPageLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(NewPropTitle)))
                .addGap(52, 52, 52)
                .addGroup(AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumbBedText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumbBedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuadrantText)
                    .addComponent(QuadrantInputBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PropertyTypeNewPropText)
                    .addComponent(PropTypeNewPropField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddPropertyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PriceText)
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(FurnishedBox)
                .addGap(41, 41, 41)
                .addComponent(NewPropSubmitButton)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        BackLPayFees.setText("Back");
        BackLPayFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackLPayFeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PayFeesPageLayout = new javax.swing.GroupLayout(PayFeesPage.getContentPane());
        PayFeesPage.getContentPane().setLayout(PayFeesPageLayout);
        PayFeesPageLayout.setHorizontalGroup(
            PayFeesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayFeesPageLayout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(BackLPayFees)
                .addContainerGap())
        );
        PayFeesPageLayout.setVerticalGroup(
            PayFeesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayFeesPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackLPayFees)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        BackLEditListing.setText("Back");
        BackLEditListing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackLEditListingActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Property thigs here");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EditListingPageLandlordLayout = new javax.swing.GroupLayout(EditListingPageLandlord.getContentPane());
        EditListingPageLandlord.getContentPane().setLayout(EditListingPageLandlordLayout);
        EditListingPageLandlordLayout.setHorizontalGroup(
            EditListingPageLandlordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditListingPageLandlordLayout.createSequentialGroup()
                .addContainerGap(528, Short.MAX_VALUE)
                .addComponent(BackLEditListing)
                .addContainerGap())
            .addGroup(EditListingPageLandlordLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditListingPageLandlordLayout.setVerticalGroup(
            EditListingPageLandlordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditListingPageLandlordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackLEditListing)
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        RegisterTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        RegisterTitle.setText("Register");

        EmailRegisterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailRegisterFieldActionPerformed(evt);
            }
        });

        EmailRegisterText.setText("E-Mail");

        PasswordRegisterText.setText("Password");

        RegisterRegisterButton.setText("Register");
        RegisterRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterRegisterButtonActionPerformed(evt);
            }
        });

        ResetRegisterButton.setText("Reset");
        ResetRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetRegisterButtonActionPerformed(evt);
            }
        });

        ComboRegisterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Landlord", "Admin" }));
        ComboRegisterBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRegisterBoxActionPerformed(evt);
            }
        });

        AccountRegisterType.setText("AccountType");

        PasswordRegisterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordRegisterFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterPageLayout = new javax.swing.GroupLayout(RegisterPage.getContentPane());
        RegisterPage.getContentPane().setLayout(RegisterPageLayout);
        RegisterPageLayout.setHorizontalGroup(
            RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPageLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterPageLayout.createSequentialGroup()
                        .addComponent(RegisterRegisterButton)
                        .addGap(100, 100, 100)
                        .addComponent(ResetRegisterButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterPageLayout.createSequentialGroup()
                            .addComponent(EmailRegisterText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                            .addComponent(EmailRegisterField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterPageLayout.createSequentialGroup()
                            .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PasswordRegisterText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AccountRegisterType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ComboRegisterBox, 0, 116, Short.MAX_VALUE)
                                .addComponent(PasswordRegisterField))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterPageLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(RegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        RegisterPageLayout.setVerticalGroup(
            RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(RegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailRegisterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailRegisterText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordRegisterText)
                    .addComponent(PasswordRegisterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboRegisterBox, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountRegisterType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(RegisterPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterRegisterButton)
                    .addComponent(ResetRegisterButton))
                .addGap(42, 42, 42))
        );

        BackFees.setText("Back");
        BackFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChangeFeesPageLayout = new javax.swing.GroupLayout(ChangeFeesPage.getContentPane());
        ChangeFeesPage.getContentPane().setLayout(ChangeFeesPageLayout);
        ChangeFeesPageLayout.setHorizontalGroup(
            ChangeFeesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangeFeesPageLayout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(BackFees)
                .addGap(18, 18, 18))
        );
        ChangeFeesPageLayout.setVerticalGroup(
            ChangeFeesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangeFeesPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackFees)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        AdminDashboardText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminDashboardText.setText("Admin Dashboard");

        GoMainPageAdminButton.setText("Go to Main Page");
        GoMainPageAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoMainPageAdminButtonActionPerformed(evt);
            }
        });

        EditListingsAdminButton.setText("Edit Listings");
        EditListingsAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditListingsAdminButtonActionPerformed(evt);
            }
        });

        ChnageFeesButton.setText("Change Fees");

        RequestSummmaryButton.setText("Request Summary");

        javax.swing.GroupLayout AdminDashboardPageLayout = new javax.swing.GroupLayout(AdminDashboardPage.getContentPane());
        AdminDashboardPage.getContentPane().setLayout(AdminDashboardPageLayout);
        AdminDashboardPageLayout.setHorizontalGroup(
            AdminDashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminDashboardPageLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(GoMainPageAdminButton)
                .addGap(18, 18, 18)
                .addComponent(EditListingsAdminButton)
                .addGap(18, 18, 18)
                .addComponent(ChnageFeesButton)
                .addGap(26, 26, 26)
                .addComponent(RequestSummmaryButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminDashboardPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDashboardText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        AdminDashboardPageLayout.setVerticalGroup(
            AdminDashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminDashboardPageLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(AdminDashboardText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(AdminDashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoMainPageAdminButton)
                    .addComponent(EditListingsAdminButton)
                    .addComponent(ChnageFeesButton)
                    .addComponent(RequestSummmaryButton))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        LandlordDashboardTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LandlordDashboardTitle.setText("Landlord Dashboard");

        RegisterPropertyLandlord.setText("Register Property");
        RegisterPropertyLandlord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPropertyLandlordActionPerformed(evt);
            }
        });

        PayFeesLandlord.setText("Pay Fees");
        PayFeesLandlord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayFeesLandlordActionPerformed(evt);
            }
        });

        EditListingsLandlord.setText("Edit Listings");
        EditListingsLandlord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditListingsLandlordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LandlordDashboardPageLayout = new javax.swing.GroupLayout(LandlordDashboardPage.getContentPane());
        LandlordDashboardPage.getContentPane().setLayout(LandlordDashboardPageLayout);
        LandlordDashboardPageLayout.setHorizontalGroup(
            LandlordDashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LandlordDashboardPageLayout.createSequentialGroup()
                .addGroup(LandlordDashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LandlordDashboardPageLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(RegisterPropertyLandlord)
                        .addGap(18, 18, 18)
                        .addComponent(PayFeesLandlord)
                        .addGap(32, 32, 32)
                        .addComponent(EditListingsLandlord))
                    .addGroup(LandlordDashboardPageLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(LandlordDashboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        LandlordDashboardPageLayout.setVerticalGroup(
            LandlordDashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LandlordDashboardPageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LandlordDashboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(LandlordDashboardPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterPropertyLandlord)
                    .addComponent(PayFeesLandlord)
                    .addComponent(EditListingsLandlord))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        LoginText.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LoginText.setText("Login Page");

        UsernameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsernameText.setText("Email");

        PasswordText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PasswordText.setText("Password");

        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });

        ResultText.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPageLayout = new javax.swing.GroupLayout(LoginPage.getContentPane());
        LoginPage.getContentPane().setLayout(LoginPageLayout);
        LoginPageLayout.setHorizontalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordText)
                    .addComponent(UsernameText)
                    .addComponent(LoginButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPageLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(ResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPageLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(LoginText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPageLayout.setVerticalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LoginText, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameText)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordText))
                .addGap(36, 36, 36)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetButton)
                    .addComponent(LoginButton))
                .addGap(34, 34, 34)
                .addComponent(ResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BackAEditListings.setText("Back");
        BackAEditListings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackAEditListingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditListingPageAdminLayout = new javax.swing.GroupLayout(EditListingPageAdmin.getContentPane());
        EditListingPageAdmin.getContentPane().setLayout(EditListingPageAdminLayout);
        EditListingPageAdminLayout.setHorizontalGroup(
            EditListingPageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditListingPageAdminLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(BackAEditListings, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        EditListingPageAdminLayout.setVerticalGroup(
            EditListingPageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditListingPageAdminLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BackAEditListings)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginHomeButton.setText("Login");
        LoginHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginHomeButtonActionPerformed(evt);
            }
        });

        RegisterHomeButton.setText("Register");
        RegisterHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterHomeButtonActionPerformed(evt);
            }
        });

        EnterHomeButton.setText("Enter");
        EnterHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterHomeButtonActionPerformed(evt);
            }
        });

        WelcomeText.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        WelcomeText.setText("Welcome!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(LoginHomeButton)
                        .addGap(32, 32, 32)
                        .addComponent(RegisterHomeButton)
                        .addGap(36, 36, 36)
                        .addComponent(EnterHomeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(WelcomeText)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(WelcomeText)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginHomeButton)
                    .addComponent(RegisterHomeButton)
                    .addComponent(EnterHomeButton))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        LoginCheck();
        
    }                                           

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        UsernameField.setText("");
        PasswordField.setText("");
    }                                           

    private void LoginHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        GoLogin();
    }                                               

    private void RegisterRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        usertype=ComboRegisterBox.getSelectedItem()+"";
        GoRMain();
       
        // System.out.println("Account type: "+ComboRegisterBox.getSelectedItem());
    }                                                      

    private void ComboRegisterBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       
    }                                                

    private void RegisterHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        GoRegister();
    }                                                  

    private void ResetRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        EmailRegisterField.setText("");
        PasswordRegisterField.setText("");
    }                                                   

    private void EnterHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
      GoMain();
    }                                               

    private void EmailRegisterFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void RegisterPropertyLandlordActionPerformed(java.awt.event.ActionEvent evt) {                                                         
       LandlordDashboardPage.setVisible(false);
       
       AddPropertyPage.setVisible(true);
       AddPropertyPage.pack();
    }                                                        

    private void PasswordRegisterFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void PayFeesLandlordActionPerformed(java.awt.event.ActionEvent evt) {                                                
  LandlordDashboardPage.setVisible(false);
       
       PayFeesPage.setVisible(true);
       PayFeesPage.pack();        
    }                                               

    private void EditListingsLandlordActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        LandlordDashboardPage.setVisible(false);
       
      EditListingPageLandlord.setVisible(true);
       EditListingPageLandlord.pack();   
    }                                                    

    private void GoMainPageAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        GoAMain();
    }                                                     

    private void EditListingsAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
     AdminDashboardPage.setVisible(false);
     EditListingPageLandlord.setVisible(true);
     EditListingPageLandlord.pack();
    }                                                       

    private void BackFeesActionPerformed(java.awt.event.ActionEvent evt) {                                         
       GoBackADash(ChangeFeesPage);
    }                                        

    private void BackLEditListingActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        GoBackLDash(EditListingPageLandlord);
    }                                                

    private void BackLAddPropActionPerformed(java.awt.event.ActionEvent evt) {                                             
        GoBackLDash(AddPropertyPage);
    }                                            

    private void BackLPayFeesActionPerformed(java.awt.event.ActionEvent evt) {                                             
         GoBackLDash(PayFeesPage);
    }                                            

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void BackAEditListingsActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        GoBackADash(EditListingPageAdmin);
    }                                                 
     private void GoLogin(){
           this.setVisible(false);
             LoginPage.pack();
               LoginPage.setVisible(true);
     }
      
      private void GoBackADash(javax.swing.JFrame page){
           page.setVisible(false);
             AdminDashboardPage.pack();
              AdminDashboardPage.setVisible(true);
     }
       private void GoBackLDash(javax.swing.JFrame page){
           page.setVisible(false);
             LandlordDashboardPage.pack();
              LandlordDashboardPage.setVisible(true);
     }
      private void GoRegister(){
       this.setVisible(false);
       RegisterPage.pack();
       RegisterPage.setVisible(true);
      }
      
        private void GoMain(){
            this.setVisible(false);
         
            if(usertype.equals("Landlord")){
                LandlordDashboardPage.pack();
                LandlordDashboardPage.setVisible(true);
            }else if(usertype.equals("Admin")){
                  AdminDashboardPage.pack();
                AdminDashboardPage.setVisible(true);
            }else{
                MainPage.pack();
       MainPage.setVisible(true);
            }
       
      
      }
        private void GoRMain(){
       RegisterPage.setVisible(false);
      
       if(usertype.equals("Landlord")){
                LandlordDashboardPage.pack();
                LandlordDashboardPage.setVisible(true);
            }else if(usertype.equals("Admin")){
                  AdminDashboardPage.pack();
                AdminDashboardPage.setVisible(true);
            }else{
                MainPage.pack();
       MainPage.setVisible(true);
            }
      }
        private void GoAMain(){
       AdminDashboardPage.setVisible(false);
      
       MainPage.pack();
       MainPage.setVisible(true);
            
      }
    private void LoginCheck(){
        boolean status = false;
        String Utemp = "admin";
        String Ptemp = "password";
          
        System.out.println("Username Field: "+UsernameField.getText());
        if(Utemp.equals(UsernameField.getText()) && Ptemp.equals(PasswordField.getText())){
             status = true;
        }
        
        if(status){
            ResultText.setText("Login Successful");
             ResultText.setForeground(Color.BLUE);
            // dispose();
             LoginPage.setVisible(false);
             MainPage.pack();
              MainPage.setVisible(true);
          
              
             
        }else{
             ResultText.setText("Invalid Credentials");
               ResultText.setForeground(Color.RED);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               View v1 =new View();
                       v1.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel AccountRegisterType;
    private javax.swing.JFrame AddPropertyPage;
    private javax.swing.JFrame AdminDashboardPage;
    private javax.swing.JLabel AdminDashboardText;
    private javax.swing.JButton BackAEditListings;
    private javax.swing.JButton BackFees;
    private javax.swing.JButton BackLAddProp;
    private javax.swing.JButton BackLEditListing;
    private javax.swing.JButton BackLPayFees;
    private javax.swing.JFrame ChangeFeesPage;
    private javax.swing.JButton ChnageFeesButton;
    private javax.swing.JComboBox<String> ComboRegisterBox;
    private javax.swing.JFrame EditListingPageAdmin;
    private javax.swing.JFrame EditListingPageLandlord;
    private javax.swing.JButton EditListingsAdminButton;
    private javax.swing.JButton EditListingsLandlord;
    private javax.swing.JTextField EmailRegisterField;
    private javax.swing.JLabel EmailRegisterText;
    private javax.swing.JToggleButton EnterHomeButton;
    private javax.swing.JCheckBox FurnishedBox;
    private javax.swing.JButton GoMainPageAdminButton;
    private javax.swing.JFrame LandlordDashboardPage;
    private javax.swing.JLabel LandlordDashboardTitle;
    private javax.swing.JButton LoginButton;
    private javax.swing.JToggleButton LoginHomeButton;
    private javax.swing.JFrame LoginPage;
    private javax.swing.JLabel LoginText;
    private javax.swing.JFrame MainPage;
    private javax.swing.JPanel MainPagePanel;
    private javax.swing.JLabel NameHereText;
    private javax.swing.JButton NewPropSubmitButton;
    private javax.swing.JLabel NewPropTitle;
    private javax.swing.JSpinner NumbBedSpinner;
    private javax.swing.JLabel NumbBedText;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField PasswordRegisterField;
    private javax.swing.JLabel PasswordRegisterText;
    private javax.swing.JLabel PasswordText;
    private javax.swing.JButton PayFeesLandlord;
    private javax.swing.JFrame PayFeesPage;
    private javax.swing.JTextField PriceField;
    private javax.swing.JLabel PriceText;
    private javax.swing.JTextField PropTypeNewPropField;
    private javax.swing.JLabel PropertyTypeNewPropText;
    private javax.swing.JLabel PropietyTitle;
    private javax.swing.JComboBox<String> QuadrantInputBox;
    private javax.swing.JLabel QuadrantText;
    private javax.swing.JToggleButton RegisterHomeButton;
    private javax.swing.JFrame RegisterPage;
    private javax.swing.JButton RegisterPropertyLandlord;
    private javax.swing.JButton RegisterRegisterButton;
    private javax.swing.JLabel RegisterTitle;
    private javax.swing.JButton RequestSummmaryButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton ResetRegisterButton;
    private javax.swing.JLabel ResultText;
    private javax.swing.JLabel ThingsHereText;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameText;
    private javax.swing.JButton ViewButton;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
